### ISSUE TITLE
启动manager报没有找到app.ini文件

### ISSUE THREAD

**Issue by drone789** [netxfly/x-proxy#1]
time="2019-04-27T22:16:11+08:00" level=panic msg="open conf/app.ini: no such file or directory" prefix="x-proxy Manager"
panic: (*logrus.Entry) (0x152c540,0xc0000d5180)

x-proxy/manager/settings.init.0()
	/XXX/src/x-proxy/manager/settings/settings.go:44 +0xe9

**Comment by netxfly** [comment]
是在manager目录中启动的吗？如果用supervisor启动时，需要指定下工作目录。示例如下：
```ini
[program:xproxy_manager]
command=/data/golang/src/x-proxy/manager/manager
directory=/data/golang/src/x-proxy/manager/
autostart=true
startsecs=5
stdout_logfile=/tmp/xproxy_manager.out
stderr_logfile=/tmp/xproxy_manager.err
```
